Update deployment script for Cloud Run
mwvgroup/pittgoogle-user pull request #9
Opened 2022-10-26 21:17 UTC by hernandezc1

Objectives:

- [ ] create the necessary Pub/Sub topic(s) and subscription(s)
- [ ] create the BigQuery dataset and table(s)
- [ ] instruct Cloud Build to containerize the module and deploy it to Cloud Run

2023-01-12 09:07 UTC, troyraen requested changes
It's getting there. I left a few specific comments below. Most important are the "topic" in setup.sh and the publish time in classifier/main.py.

2023-01-12 09:07 UTC, troyraen commented on setup.sh
> +runinvoker_svcact="cloud-run-invoker@${GOOGLE_CLOUD_PROJECT}.iam.gserviceaccount.com"
For consistency, let's use `PROJECT_ID` here instead of `GOOGLE_CLOUD_PROJECT`.

2023-01-12 09:07 UTC, troyraen commented on setup.sh
> +topic="elasticc-loop"
I'm confused by the inclusion of both `topic` (here) and `pubsub_trigger_topic` (line 14). We should not need both for the same deployment. 

We will want to attach the classifier to different topics depending on whether we are deploying a testing instance or a production instance. So I think it would be better to make both the topic and the topic project arguments to this script rather than choosing one and hard-coding it in.

2023-01-12 09:07 UTC, troyraen commented on setup.sh
> +fi
For clarity, let's re-order these lines like this:
- first, define the variables that need a testid
- then do the `if` statement attaching the testid
- then define the rest of the variables

2023-01-12 09:07 UTC, troyraen commented on setup.sh
> +    gcloud pubsub topics create "${pubsub_trigger_topic}"
I think this script should assume that `pubsub_trigger_topic` already exists. This topic only needs to be created in certain cases, and only for testing deployments. Often it will live in an external project, and we should assume that the user of this script does not have permission to create a topic in that project.

2023-01-12 09:07 UTC, troyraen commented on setup.sh
> +        gcloud pubsub topics delete "${pubsub_trigger_topic}"
As above, let's remove the creation/deletion of `pubsub_trigger_topic` from this script. Our instructions for using this script should include information about this topic (i.e., both options: connecting to a topic produced by our ELAsTiCC broker and creating their own topic for testing), but I think this script should not administer it directly.

2023-01-12 09:07 UTC, troyraen commented on setup.sh
> +    fi
We should also delete the Cloud Run service ([this](https://cloud.google.com/sdk/gcloud/reference/run/services/delete) command) and the container ([this](https://cloud.google.com/sdk/gcloud/reference/container/images/delete) command). Resource names should be in the file cloudbuild.yaml.

2023-01-12 09:07 UTC, troyraen commented on classifier/main.py
> +        "brokerIngestTimestamp": datetime.strptime(msg["publish_time"].replace("Z","+00:00"), '%Y-%m-%dT%H:%M:%S.%f%z'),
Looks to me like this line is still erroring (I tested it on Jan 12; see [Error Reporting](https://console.cloud.google.com/errors/detail/CLXo76rHp76u-gE;time=P1D?project=elasticc-challenge)). From what I can tell right now, I think the datetimes are coming in with different precisions, so sometimes they need the `.%f` and sometimes they don't.

Let's try defining the variable like this, somewhere before line 81:

```python
try:
    publish_time = datetime.strptime(msg["publish_time"].replace("Z","+00:00"), '%Y-%m-%dT%H:%M:%S.%f%z')
except ValueError:
    publish_time = datetime.strptime(msg["publish_time"].replace("Z","+00:00"), '%Y-%m-%dT%H:%M:%S%z')
```

Then line 83 should be:

```python
"brokerIngestTimestamp": publish_time,
```

2023-01-12 17:09 UTC, hernandezc1 commented on setup.sh
> +fi
Got it. Made the changes and added the variables needed for the "gcloud run services/container images delete" command

2023-03-02 21:42 UTC, troyraen approved these changes
Looks good, nice work! Let's remove the ztf-specific files for now and just focus on running elasticc. Otherwise I think this is ready to merge.

2023-03-04 17:06 UTC, merged